USE [master]
GO

/****** Object:  Database [MoogaBox]    Script Date: 2022-05-23 ¿ÀÀü 9:10:52 ******/
CREATE DATABASE [MoogaBox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoogaBox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MoogaBox.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoogaBox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MoogaBox_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MoogaBox] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoogaBox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoogaBox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoogaBox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoogaBox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoogaBox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoogaBox] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoogaBox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoogaBox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoogaBox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoogaBox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoogaBox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoogaBox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoogaBox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoogaBox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoogaBox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoogaBox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoogaBox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoogaBox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoogaBox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoogaBox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoogaBox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoogaBox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoogaBox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoogaBox] SET RECOVERY FULL 
GO

ALTER DATABASE [MoogaBox] SET  MULTI_USER 
GO

ALTER DATABASE [MoogaBox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoogaBox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoogaBox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoogaBox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoogaBox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoogaBox] SET QUERY_STORE = OFF
GO

USE [MoogaBox]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [MoogaBox] SET  READ_WRITE 
GO


